const statuses=["待投","已投","待确认","待筛岗位","监控中","笔试","面试","Offer","系统受阻","结束"];
const quickActions=["","今天投递","筛选岗位","等待结果","准备笔试","准备面试","跟进HR","等待开放"];
const loginMethods=["待确定","手机","手机/短信","微信","微信扫码","邮箱","邮箱账号","官网账号","第三方平台","线下/其他"];
const priorities=["P0","P1","P2","-"];
const $=s=>document.querySelector(s); let jobs=[]; let draggedId=null; let selectedStatuses=new Set();
const escape=s=>String(s??"").replace(/[&<>\"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const remaining=j=>j.totalChances===null||j.totalChances===""?"待核实":Math.max(0,Number(j.totalChances)-Number(j.appliedCount||0));
const statusClass=s=>["已投","笔试","面试","Offer"].includes(s)?"status-applied":["系统受阻","无合适岗位","不合适","结束"].includes(s)?"status-blocked":"status-todo";
async function api(url,options={}){let list=JSON.parse(localStorage.getItem("campus-demo-jobs")||"null");if(!Array.isArray(list)){list=await fetch("./data/jobs.json").then(r=>r.json());localStorage.setItem("campus-demo-jobs",JSON.stringify(list))}const method=options.method||"GET";if(url==="/api/jobs"&&method==="GET")return list;if(url==="/api/jobs"&&method==="POST"){const item={...JSON.parse(options.body),id:"demo-"+Date.now(),order:list.length};list.push(item);localStorage.setItem("campus-demo-jobs",JSON.stringify(list));return item}if(url==="/api/jobs/reorder"){const ids=JSON.parse(options.body).ids;list.sort((a,b)=>ids.indexOf(a.id)-ids.indexOf(b.id));localStorage.setItem("campus-demo-jobs",JSON.stringify(list));return {ok:true}}const id=decodeURIComponent(url.split("/").pop());if(method==="PATCH"){const patch=JSON.parse(options.body);list=list.map(x=>x.id===id?{...x,...patch}:x);localStorage.setItem("campus-demo-jobs",JSON.stringify(list));return list.find(x=>x.id===id)}if(method==="DELETE"){list=list.filter(x=>x.id!==id);localStorage.setItem("campus-demo-jobs",JSON.stringify(list));return {ok:true}}throw new Error("不支持的演示操作")}
async function patchJob(id,payload,row){const updated=await api(`/api/jobs/${id}`,{method:"PATCH",body:JSON.stringify(payload)});jobs=jobs.map(j=>j.id===id?updated:j);if(row){row.classList.remove("save-flash");void row.offsetWidth;row.classList.add("save-flash")}renderStats()}
function renderStats(){const count=s=>jobs.filter(j=>s.includes(j.status)).length;const cards=[["全部公司",jobs.length],["已经投递",count(["已投","笔试","面试","Offer"])],["等待处理",count(["待投","待确认","待筛岗位","等待开放"])],["高成长企业",jobs.filter(j=>j.category==="高成长公司").length],["机构投资企业",jobs.filter(j=>j.category==="机构投资企业").length]];$("#stats").innerHTML=cards.map(x=>`<article class="stat"><span>${x[0]}</span><strong>${x[1]}</strong></article>`).join("")}
function filtered(){const q=$("#search").value.trim().toLowerCase(),c=$("#categoryFilter").value,p=$("#priorityFilter").value,mode=$("#sortMode").value;const list=jobs.filter(j=>(!q||[j.company,j.role,j.location,j.notes].join(" ").toLowerCase().includes(q))&&(!selectedStatuses.size||selectedStatuses.has(j.status))&&(!c||j.category===c)&&(!p||j.priority===p));const pRank={P0:0,P1:1,P2:2,"-":3},sRank={待投:0,待确认:1,待筛岗位:2,等待开放:3,监控中:4,已投:5,笔试:6,面试:7,Offer:8,系统受阻:9,无合适岗位:10,不合适:11,结束:12};return list.sort((a,b)=>mode==="priority"?pRank[a.priority]-pRank[b.priority]:mode==="status"?sRank[a.status]-sRank[b.status]:mode==="deadline"?(a.deadline||"9999").localeCompare(b.deadline||"9999"):mode==="company"?a.company.localeCompare(b.company,"zh-CN"):(a.order??jobs.indexOf(a))-(b.order??jobs.indexOf(b)))}
const options=(items,current)=>items.map(x=>`<option ${x===current?"selected":""}>${escape(x)}</option>`).join("");
function aiNote(j){const left=remaining(j),deadline=j.deadline&&/^\d{4}-\d{2}-\d{2}$/.test(j.deadline)?Math.ceil((new Date(j.deadline+"T23:59:59")-new Date())/86400000):null;if(["已投","笔试","面试","Offer"].includes(j.status))return j.status==="已投"?"已完成投递，留意笔面试通知":`当前${j.status}阶段，按下一步动作准备`;if(["系统受阻","无合适岗位"].includes(j.status))return j.status==="系统受阻"?"投递入口受阻，建议稍后重试":"暂无匹配岗位，继续监控";if(deadline!==null&&deadline<0)return"截止日期已过，请核验状态";if(deadline!==null&&deadline<=3)return`临近截止，仅剩${Math.max(0,deadline)}天`;if(left===0)return"投递机会已用完，等待后续结果";if(j.status==="待投")return j.priority==="P0"?"高匹配机会，建议今天优先投":"尚未投递，建议尽快处理";if(j.status==="待筛岗位")return"先核对地点、毕业时间和岗位要求";if(j.status==="监控中")return"暂未确认合适岗位，系统持续监控";return j.notes?j.notes.slice(0,38):"信息不完整，建议补充或核实"}
function actionOptions(j){const values=[j.nextAction,...quickActions].filter((x,i,a)=>x&&a.indexOf(x)===i);return `<option value="">选择下一步</option>`+values.map(x=>`<option value="${escape(x)}" ${j.nextAction===x?"selected":""}>${escape(x)}</option>`).join("")}
function loginOptions(j){const current=j.loginMethod||"待确定",values=[current,...loginMethods].filter((x,i,a)=>x&&a.indexOf(x)===i);return options(values,current)}
function render(){renderStats();const list=filtered(),manual=$("#sortMode").value==="manual";$("#resultCount").innerHTML=`${list.length} 条${manual?' · <span class="manual-hint">拖动左侧把手调整顺序</span>':""}`;$("#empty").hidden=!!list.length;$("#jobsBody").innerHTML=list.map(j=>`<tr data-id="${j.id}" draggable="${manual}"><td><span class="drag-handle" title="拖动排序">⋮⋮</span></td><td><button class="badge ${escape(j.priority)} priority-btn" data-priority="${j.id}" title="点击切换优先级">${escape(j.priority)}</button></td><td><span class="company">${escape(j.company)}</span><span class="role">${escape(j.role)||"未填写方向"}</span></td><td>${escape(j.location)||'<span class="empty-cell">待补充</span>'}</td><td><select class="inline-select ${statusClass(j.status)}" data-status="${j.id}">${options(statuses.includes(j.status)?statuses:[j.status,...statuses],j.status)}</select></td><td><div class="chance-control"><button class="mini-btn" data-count="down" data-id="${j.id}">−</button><input class="count-input" type="number" min="0" value="${Number(j.appliedCount||0)}" data-count-input="${j.id}" aria-label="${escape(j.company)}已投次数"><span>/</span><input class="count-input total-input" type="number" min="0" placeholder="?" value="${j.totalChances??""}" data-total-input="${j.id}" aria-label="${escape(j.company)}总投递机会"><button class="mini-btn" data-count="up" data-id="${j.id}">＋</button></div></td><td><select class="inline-select login-select" data-login="${j.id}" aria-label="${escape(j.company)}登录方式">${loginOptions(j)}</select></td><td><textarea class="user-note-input" rows="2" placeholder="点击填写" data-user-notes="${j.id}" aria-label="${escape(j.company)}我的备注">${escape(j.userNotes)}</textarea></td><td><span class="ai-note ${statusClass(j.status)}">${escape(aiNote(j))}</span></td><td>${escape(j.deadline)||"—"}</td><td>${j.url?`<a class="link" href="${escape(j.url)}" target="_blank" rel="noreferrer">打开 ↗</a>`:"—"}</td><td><button class="row-action" data-edit="${j.id}" title="更多字段">•••</button></td></tr>`).join("");bindDrag(manual)}
function bindDrag(enabled){if(!enabled)return;document.querySelectorAll("#jobsBody tr").forEach(row=>{row.ondragstart=()=>{draggedId=row.dataset.id;row.classList.add("dragging")};row.ondragend=()=>{draggedId=null;row.classList.remove("dragging");document.querySelectorAll(".drag-over").forEach(x=>x.classList.remove("drag-over"))};row.ondragover=e=>{e.preventDefault();if(row.dataset.id!==draggedId)row.classList.add("drag-over")};row.ondragleave=()=>row.classList.remove("drag-over");row.ondrop=async e=>{e.preventDefault();row.classList.remove("drag-over");const ids=filtered().map(j=>j.id),from=ids.indexOf(draggedId),to=ids.indexOf(row.dataset.id);if(from<0||to<0||from===to)return;ids.splice(to,0,ids.splice(from,1)[0]);await api("/api/jobs/reorder",{method:"POST",body:JSON.stringify({ids})});jobs.forEach(j=>{const i=ids.indexOf(j.id);if(i>=0)j.order=i});render()}})}
function populateFilters(){const add=(el,vals)=>vals.forEach(x=>{const o=document.createElement("option");o.value=o.textContent=x;el.append(o)});add($("#categoryFilter"),[...new Set(jobs.map(j=>j.category))]);add($("#jobForm select[name=status]"),statuses);renderStatusChoices()}
function renderStatusChoices(filter=""){const actual=[...new Set(jobs.map(j=>j.status))],visible=actual.filter(x=>x.includes(filter));$("#statusChoices").innerHTML=visible.map(x=>`<label><input type="checkbox" value="${escape(x)}" ${!selectedStatuses.size||selectedStatuses.has(x)?"checked":""}><span>${escape(x)}</span><small>${jobs.filter(j=>j.status===x).length}</small></label>`).join("")}
function openEditor(job={}){const f=$("#jobForm");f.reset();for(const [k,v] of Object.entries(job))if(f.elements[k])f.elements[k].value=v??"";$("#dialogHeading").textContent=job.id?"编辑更多信息":"添加机会";$("#deleteBtn").hidden=!job.id;$("#editor").showModal()}
function syncStickyOffset(){document.documentElement.style.setProperty("--toolbar-sticky-height",`${$(".toolbar").offsetHeight}px`)}
async function load(){jobs=await api("/api/jobs");populateFilters();render();syncStickyOffset()}
$("#jobsBody").onchange=async e=>{const row=e.target.closest("tr");if(e.target.dataset.status){await patchJob(e.target.dataset.status,{status:e.target.value},row);return render()}if(e.target.dataset.login){await patchJob(e.target.dataset.login,{loginMethod:e.target.value},row);return render()}if(e.target.dataset.userNotes){await patchJob(e.target.dataset.userNotes,{userNotes:e.target.value.trim()},row);return render()}if(e.target.dataset.countInput){const n=Math.max(0,Number(e.target.value||0));await patchJob(e.target.dataset.countInput,{appliedCount:n},row);return render()}if(e.target.dataset.totalInput){const n=e.target.value===""?null:Math.max(0,Number(e.target.value));await patchJob(e.target.dataset.totalInput,{totalChances:n},row);return render()}};
$("#jobsBody").onclick=async e=>{const row=e.target.closest("tr"),id=e.target.dataset.id||e.target.dataset.priority||e.target.dataset.applied||e.target.dataset.edit;if(e.target.dataset.edit)return openEditor(jobs.find(j=>j.id===id));if(e.target.dataset.priority){const j=jobs.find(x=>x.id===id),next=priorities[(priorities.indexOf(j.priority)+1)%priorities.length];await patchJob(id,{priority:next},row);return render()}if(e.target.dataset.count){const j=jobs.find(x=>x.id===id),n=Math.max(0,Number(j.appliedCount||0)+(e.target.dataset.count==="up"?1:-1));await patchJob(id,{appliedCount:n},row);return render()}if(e.target.dataset.applied){const j=jobs.find(x=>x.id===id);await patchJob(id,{status:"已投",appliedCount:Math.max(1,Number(j.appliedCount||0)+1),nextAction:"等待结果"},row);return render()}};
$("#addBtn").onclick=()=>openEditor();$("#closeDialog").onclick=$("#cancelBtn").onclick=()=>$("#editor").close();
for(const id of ["search","categoryFilter","priorityFilter"])$("#"+id).addEventListener(id==="search"?"input":"change",render);$("#sortMode").onchange=render;
$("#statusSearch").oninput=e=>renderStatusChoices(e.target.value.trim());$("#statusAll").onchange=e=>document.querySelectorAll('#statusChoices input').forEach(x=>x.checked=e.target.checked);$("#statusConfirm").onclick=()=>{const boxes=[...document.querySelectorAll('#statusChoices input')],picked=boxes.filter(x=>x.checked).map(x=>x.value);selectedStatuses=picked.length===boxes.length?new Set():new Set(picked);$("#statusFilter summary").textContent=selectedStatuses.size?`已选 ${selectedStatuses.size} 项`:"全部状态";$("#statusFilter").open=false;render()};$("#statusCancel").onclick=()=>{$("#statusFilter").open=false;renderStatusChoices()};
$("#clearFilters").onclick=()=>{for(const id of ["search","categoryFilter","priorityFilter"])$("#"+id).value="";selectedStatuses=new Set();$("#statusFilter summary").textContent="全部状态";$("#statusAll").checked=true;renderStatusChoices();render()};
$("#jobForm").onsubmit=async e=>{e.preventDefault();const payload=Object.fromEntries(new FormData(e.currentTarget));payload.appliedCount=Number(payload.appliedCount||0);payload.totalChances=payload.totalChances===""?null:Number(payload.totalChances);const id=payload.id;delete payload.id;if(id)await api(`/api/jobs/${id}`,{method:"PATCH",body:JSON.stringify(payload)});else await api("/api/jobs",{method:"POST",body:JSON.stringify(payload)});$("#editor").close();jobs=await api("/api/jobs");render()};
$("#deleteBtn").onclick=async()=>{const id=$("#jobForm").elements.id.value;if(id&&confirm("确认删除这条机会？")){await api(`/api/jobs/${id}`,{method:"DELETE"});$("#editor").close();jobs=await api("/api/jobs");render()}};
window.addEventListener("resize",syncStickyOffset);load().catch(e=>alert(e.message));setInterval(async()=>{if(!$("#editor").open){try{jobs=await api("/api/jobs");render();syncStickyOffset()}catch{}}},60000);
window.addEventListener("message",async event=>{
  const message=event.data;
  if(message?.source!=="lifecontrol-hub"||!message.type?.startsWith("backup:"))return;
  const reply=(ok,data,error)=>event.source?.postMessage({source:"lifecontrol-app",requestId:message.requestId,ok,data,error},event.origin);
  try{
    if(message.type==="backup:export"){const current=await api("/api/jobs");jobs=current;return reply(true,{jobs:current})}
    if(message.type==="backup:import"){
      if(!Array.isArray(message.data?.jobs))throw new Error("校招备份数据格式不正确");
      await api("/api/backup",{method:"PUT",body:JSON.stringify({jobs:message.data.jobs})});jobs=message.data.jobs;render();return reply(true,{restored:true});
    }
  }catch(error){reply(false,null,error.message)}
});
